version: 1

project: "przlsglh8"
type: "multi-grpc"
ports: "5000"

worker:
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1 #[required for multi-node]
parameter-server: #[required for multi-node]
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1

checks:
  tensorflow:loss:
    target: "0.0..0.5"
    aggregate: "mean"
  defaults: #[optional]
    precision: 3
